### ISSUE TITLE
Master reference excel - SpatialTransformer

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#24]
When we are loading data from a database, we do not need the master reference excel sheet, can we please only make this parameter a requirement when the 'datatracker' input is chosen? Thanks!

**Comment by AnthonyRodway** [comment]
The commit corresponding to this issue is https://github.com/cat-cfs/twobilliontoolkit/commit/0c015607de4029ed3b9b05f367962602509cf0c5

Changes:
- master data path now only required when --load is 'datatracker'
- project numbers now pulled from the database in other cases than the above
- altered the validation and logic of creating parameters based on the above changes.
- added new function and method to compare the project numbers to support this new logic

**Comment by nesdolya** [comment]
Tested and functioning
