### ISSUE TITLE
SpatialTransformer - DataTracker functionality

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#31]
The new Salesforce data has a new project number field. I is now called: BT_Legacy_Project_ID__c
Please ensure that this field is used to gather the project numbers when --load is 'datatracker'
Note on handling the data in this field - It is possible that BT_Legacy_Project_ID__c is blank in some cases.

**Comment by AnthonyRodway** [comment]
Change has been made in the commit: https://github.com/cat-cfs/twobilliontoolkit/commit/d7885c5293978dfb8c2064bc85227a701e3141fa

Changes:
- The field that is used to gather the project numbers from the master data sheet when --load is set to 'datatracker' is now _BT_Legacy_Project_ID__c_ instead of _Project Number_

**Comment by AnthonyRodway** [comment]
@nesdolya I could not find a suitable master datasheet to test this on, so before we close this I would like to test even though the change is simple.

**Comment by nesdolya** [comment]
You could use this for testing: V:\2BT\04_Program_year\2023_planting\DataAnalyses\2BT_2021_2023_PlantingActivityData_MASTER_v103.xlsx
