### ISSUE TITLE
Foreign key constraint on project number for spatial data in the GDB

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#47]
A spatial layer is added to the GDB with the incorrect project spatial id before the foreign key contraint is triggered. Please modify this so that these layers are assigned the 0000 XXX - 000 project number and appropriate project spatial id to be fixed by records reviser. In this case the warning is sufficient (no error entry needs to be added to the log file). Examples are: 2023 CFP - 430 and 2022 GNT - 717. Example dataset is located here: \\vic-fas1\projects_a\2BT\01_Data\2BT_program_data\2023\RawData\00_Unprocessed_Spatial\GCDocs_Sept102024_Fixes

![image (5)](https://github.com/user-attachments/assets/283f0cfb-e0a4-48de-8056-8d5f6082776f)
![image](https://github.com/user-attachments/assets/4fe5d1e8-2efc-46a1-96c4-cc06dc24f74b)

**Comment by AnthonyRodway** [comment]
Changes for this issues have been made in the PR https://github.com/cat-cfs/twobilliontoolkit/pull/49

A correctly formatted project number will just be given the generic 0000 XXX - 000 project number if it is not found in the database (or datasource) so that is does not throw foreign key constraints
